apiVersion: v1
kind: Pod
metadata:
  name: multi-port-pod
spec:
  containers:
  - name: echo-8080
    image: hashicorp/http-echo
    args:
      - "-listen=:8080"
      - "-text=Hello from 8080!"
    ports:
      - containerPort: 8080

  - name: echo-9090
    image: hashicorp/http-echo
    args:
      - "-listen=:9090"
      - "-text=Hello from 9090!"
    ports:
      - containerPort: 9090

